# cloudformation solution goes here

AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for DS5220 Project 1

Parameters: 
  InstanceType: 
    Description: EC2 instance that is ubuntu, t3.micro, 16gb boot vol, necessary python libs installed, pulls copy of forked repo, set bucket_name var, runs fastAPI
    Type: String
    Default: t3.micro
  KeyName:
    Type: 'AWS::EC2::KeyPair::KeyName'
  SSHLocation:
    Type: String
    Default: 216.30.181.29/32 # my specific IPv4 address (/32 so that only this IP address is allowed)





Resources:
  # S3 bucket
  DataBucket:
    Type: AWS::S3::Bucket
    # so that AWS doesn't create bucket until the SNS topic policy is set up (aka until permissions are good)
    DependsOn: SNSTopicPolicy
    Properties:
      # hardcoded bucket name so it doesn't recurse 
      BucketName: !Sub "${AWS::StackName}-sensor-data-${AWS::AccountId}"
      # below tells S3 to monitor the raw folder and then alert the SNS topic 
      NotificationConfiguration:
        TopicConfigurations:
          - Event: 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: raw/
                  - Name: suffix
                    Value: .csv
            Topic: !Ref SNSTopic

  # SNS topic
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ds5220-dp1

  # gives permission for S3 to post in SNS 
  SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics: [!Ref SNSTopic]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "s3.amazonaws.com"
            Action: "sns:Publish"
            Resource: !Ref SNSTopic
            Condition:
              ArnLike:
                # We manually construct the ARN so the policy doesn't have to wait for the bucket
                aws:SourceArn: !Sub "arn:aws:s3:::${AWS::StackName}-sensor-data-${AWS::AccountId}"


  # this means that whenver SNS gets a message, send HTTP post request to ec2 instance on port 8000 at notify endpoint
  ApiSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: http
      Endpoint: !Sub "http://${InstanceEIP}:8000/notify"
      TopicArn: !Ref SNSTopic

  # IAM role for EC2
  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action: ["sts:AssumeRole"]
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
              # allows the below actions to the data bucket 
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:ListBucket"
                Resource: 
                  - !Sub "arn:aws:s3:::${DataBucket}"
                  - !Sub "arn:aws:s3:::${DataBucket}/*"
  # make a profile so that the instance can use the role above 
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [!Ref EC2InstanceRole]

  # security  with permissions as specified in instructions 
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and FastAPI (8000)
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0

  # EC2 instance 
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-04b70fa74e45c391 # for ubuntu in us-east-1
      # referencing everything above for the info inside of instance
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref EC2InstanceProfile
      SecurityGroupIds: [!Ref EC2SecurityGroup]
      # vol size as 16
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 16
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e
          # environment variables for bucket name so py file knows what bucket to use
          echo "BUCKET_NAME=${DataBucket}" >> /etc/environment
          export BUCKET_NAME=${DataBucket}

          # install all the good stuff 
          apt-get update -y
          apt-get install -y python3-pip python3-venv git

          # clone repo 
          git clone https://github.com/sek2dcs/anomaly-detection.git /home/ubuntu/app
          chown -R ubuntu:ubuntu /home/ubuntu/app
          cd /home/ubuntu/app

          # set up python environment and install the packages that are in the txt file 
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

  # elastic IP
  InstanceEIP:
    Type: AWS::EC2::EIP

  # ties IP to the instance in case connection gets lost 
  EIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref EC2Instance
      EIP: !Ref InstanceEIP

# output the url of fastapi app 
Outputs:
  AppURL:
    Description: URL of the FastAPI app
    Value: !Sub "http://${InstanceEIP}:8000"